# -*- coding: utf-8 -*-
"""DevelopersHub_Task#01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xyhJPNOcJY3nZjGP0WtpLKoA5DVI17qu
"""

import pandas as pd #used for data manipulation
import seaborn as sns#visulaization liabrary built on top of matplotlib
import matplotlib.pyplot as plt #used for visulization of data
import re#search,match and replace patterns in text

data=pd.read_csv("/content/google_play_music_reviews.csv")#reading dataset
data.shape#print number of rows and columns

data.head()#print first few rows of dataset.By default it print 5

data.columns#print names of columns

data.info()#print information of each column

data.describe()#summarize the stats of data

data.isnull().sum()#print sum of all null values in a columns

data = data.dropna(subset=["version"])#drop the rows where we have null values

# Filter out non-numeric versions using regex (e.g., "9.0.44.478" is OK)
def extract_version_number(v):
    if re.match(r'^\d+(\.\d+)*$', str(v)):
        return float(str(v).replace('.', ''))
    return None

data['version_numeric'] = data['version'].apply(extract_version_number)

# Drop rows where version_numeric is None
data = data.dropna(subset=["version_numeric"])

plt.figure(figsize=(8, 5))
plt.scatter(data['version_numeric'], data['rating'], color='green', alpha=0.6)

plt.xlabel("App Version (numeric)")
plt.ylabel("Rating")
plt.title("Scatter Plot: Version vs Rating")
plt.grid(True)
plt.show()

sns.set(style="whitegrid")

plt.figure(figsize=(8,4))
sns.histplot(data['rating'], bins=5, kde=True, color='skyblue')
plt.title("Histogram of Rating")
plt.xlabel("Rating")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,4))
sns.histplot(data['version_numeric'], bins=5, kde=True, color='skyblue')
plt.title("Histogram of Version Number")
plt.xlabel("Version Number")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,4))
sns.boxplot(x=data['rating'],color='salmon')
plt.title("Box Plot of Rating")
plt.xlabel('Rating')
plt.show()